Srv
dsccommunity/xDnsServer pull request #130
Opened 2021-01-03 13:54 UTC by Sudman1

#### Pull Request (PR) description
This PR addresses Issue #34 by adding the ability to manage SRV resource records.

This work was based on the PR submitted by jcuzzi to implement MX record management.

#### This Pull Request (PR) fixes the following issues
- Fixes #34

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2021-01-30 17:51 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @Sudman1)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSJPY3P9Ooz24p_qM9z:-MSJPY3P9Ooz24p_qMA-:b-rjem0y) (no related file):*
Is it possible to make integration tests for this change? There is a dns sever installed in the build worker so hopefully it can be used. It is easier (for me) to review knowing the code actually works too.

---
___
*[RequiredModules.psd1, line 16 at r2](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSJP0RY7YBN2iS9ktii:-MSJP0RY7YBN2iS9ktij:b-8tf2wx) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/549fc29fcdac083654a225d10ac5bfd7b075c36e/RequiredModules.psd1#L16)):*
> ```
> '0.105.6'
> ```

I update the pipelines files in the `main` branch so we can revert this change. Rebase the changes from the main branch.


<!-- Sent from Reviewable.io -->

2021-02-03 11:54 UTC, Sudman1 commented
Integration tests have been created and I have rebased against main to get the latest updates.

2021-02-03 13:25 UTC, Sudman1 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSJPY3P9Ooz24p_qM9z:-MSc3BeS0VCj19TZvwr1:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Is it possible to make integration tests for this change? There is a dns sever installed in the build worker so hopefully it can be used. It is easier (for me) to review knowing the code actually works too.
</blockquote></details>

Done.

---
___
*[RequiredModules.psd1, line 16 at r2](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSJP0RY7YBN2iS9ktii:-MSc3EyS2XDkl7Mp7DVu:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/549fc29fcdac083654a225d10ac5bfd7b075c36e/RequiredModules.psd1#L16)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> '0.105.6'
> ```

I update the pipelines files in the `main` branch so we can revert this change. Rebase the changes from the main branch.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-03 17:21 UTC, johlju requested changes
Awesome work on this! :smiley:  I still have the tests to review but figured I give you a bit of comments to work on. I continue review as soon as I can (hopefully tomorrow). 

Ping me if you have any questions.

> Reviewed 2 of 13 files at r1, 4 of 6 files at r2, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-:-MScuCMw9HzxR78Fp2Jy:b-pxowc9)* status: 9 of 14 files reviewed, 31 unresolved discussions (waiting on @Sudman1)

___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 72 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScowb4EbE7VwuFx3aL:-MScowb4EbE7VwuFx3aM:b-sczuw0) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L72)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>         [Parameter()]
>         [System.UInt16]
>         $Priority=10,
>
>         [Parameter()]
>         [System.UInt16]
>         $Weight=20,
>
>         [Parameter()]
>         [ValidateScript({$ts = New-TimeSpan; [system.timespan]::TryParse($_, [ref]$ts)})]
>         [System.String]
>         $TTL,
> ```
</details>


These non-mandatory parameters are not used in the function, we should not add non-mandatory functions unless they is required for Get-TargetResource to work. Instead return `0` or `$null` as appropriate in the hashtable when the object does not exist.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 86 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScqOJyAIJ2vxpJlW2l:-MScqOJyAIJ2vxpJlW2m:bf4t9py) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L86)):*
> ```
> 'localhost'
> ```

Consider using [`Get-ComputerName`](https://github.com/dsccommunity/DscResource.Common#get-computername). E.g. `$DnsServer = (Get-ComputerName),`
In this case `localhost` might be suitable since this won't run cross-platform.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 89 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScpDa12rZYdoVfiO7Z:-MScpDa12rZYdoVfiO7_:b4muhst) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L89)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         [Parameter()]
>         [ValidateSet('Present','Absent')]
>         [System.String]
>         $Ensure = 'Present'
> ```
</details>


This non-mandatory parameter is not used in the function, we should not add non-mandatory functions unless they is required for Get-TargetResource to work.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 93 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScr6Ed00loYrHbSDfZ:-MScr6Ed00loYrHbSDf_:b-j7i8ta) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L93)):*
> ```
> $recordHostName = "_$($SymbolicName)._$($Protocol)".ToLower()
> ```

Can we add a blank row before this row?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 203 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSclK6n6qCFn9IzKluB:-MSclK6n6qCFn9IzKluC:b-iltzyn) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L203)):*
> ```
> $Priority=10
> ```

There is no need for a default value on this property since it should only be used when creating a new object (see other comments), so the default value can be set prior to creating the object in the code below.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 207 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSclnc3CvAckVTorUX2:-MSclnc46g9lviYx4eXN:b-fvmcvu) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L207)):*
> ```
> $Weight=20
> ```

There is no need for a default value on this property since it should only be used when creating a new object (see other comments), so the default value can be set prior to creating the object in the code below.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 210 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSco_sI8h7Igh1BXGdf:-MSco_sI8h7Igh1BXGdg:b-wji9e) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L210)):*
> ```
> TryParse($_, [ref]$ts)
> ```

We should have space after `[ref]`, e.g.  `[ref]$ts`. Throughout the functions.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 210 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScodYE0s3sLHABVvbI:-MScodYE0s3sLHABVvbJ:bvi8rjz) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L210)):*
> ```
> [system.timespan]
> ```

If we change this to PascalCase too tit follows the rest of the types: `[System.TimeSpan]`. Throughout the functions.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 224 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScmjdD91MP7XPiHBYE:-MScmjdD91MP7XPiHBYF:b-7e0vwm) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L224)):*
> ```
> $DNSParameters
> ```

We should use camelCase for variables (parameter variables should be PascalCase). Throughout.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 228 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSckmwWDeHz3qcbCe3S:-MSckmwWDeHz3qcbCe3T:bnzpobm) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L228)):*
> ```
>     $recordHostName = "_$($SymbolicName)._$($Protocol)".ToLower()
> ```

Can we add a blank row before this row?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 230 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSckcpWDzygYJBWEuee:-MSckcpWDzygYJBWEuef:b-qv4k36) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L230)):*
> ```
> $OldObj
> ```

Maybe we can name it `$existingSrvRecord` to explain what the variable contain?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 241 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScmSJl3rVT3IBTOA2-:-MScmSJl3rVT3IBTOA20:b-j3sc5k) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L241)):*
> ```
> $NewObj
> ```

Maybe we can name it `$newSrvRecord` to explain what the variable contain?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 244 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSckwJYAZ5HLIAFgCBL:-MSckwJYAZ5HLIAFgCBM:by4q8fh) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L244)):*
> ```
> $NewObj.RecordData.Priority = $Priority
> ```

We should only enforce this property if it part of the configuration, e.g. `if ($PSBo [...]

2021-02-03 17:22 UTC, johlju reviewed
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130)* status: 10 of 14 files reviewed, 31 unresolved discussions (waiting on @Sudman1)



<!-- Sent from Reviewable.io -->

2021-02-03 17:23 UTC, johlju commented
@Sudman1 most comments are just minor things, like style. Again awesome work! 🙂

2021-02-05 02:51 UTC, Sudman1 reviewed
Thanks for the vote of confidence. My work was based mostly on jcuzzi's awesome work with the xDnsRecordMx resource.

Azure Pipelines is degraded, so I'm not 100% on the integration tests, but I didn't want to lose my reviewable session, so I am submitting this before the pipeline is complete. If there are any integration issues, I'll address them tomorrow.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-:-MSk4P4t2_IRns834HHv:b-1swinp)* status: 6 of 15 files reviewed, 31 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 72 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScowb4EbE7VwuFx3aL:-MSk1DRGDPIOs3cF4S8_:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         [Parameter()]
>         [System.UInt16]
>         $Priority=10,
>
>         [Parameter()]
>         [System.UInt16]
>         $Weight=20,
>
>         [Parameter()]
>         [ValidateScript({$ts = New-TimeSpan; [system.timespan]::TryParse($_, [ref]$ts)})]
>         [System.String]
>         $TTL,
> ```

These non-mandatory parameters are not used in the function, we should not add non-mandatory functions unless they is required for Get-TargetResource to work. Instead return `0` or `$null` as appropriate in the hashtable when the object does not exist.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 86 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScqOJyAIJ2vxpJlW2l:-MSk1Flp5YjDFhR56RF_:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L86)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'localhost'
> ```

Consider using [`Get-ComputerName`](https://github.com/dsccommunity/DscResource.Common#get-computername). E.g. `$DnsServer = (Get-ComputerName),`
In this case `localhost` might be suitable since this won't run cross-platform.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 89 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScpDa12rZYdoVfiO7Z:-MSk1ZI1EgHzZ1DNDIMy:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L89)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         [Parameter()]
>         [ValidateSet('Present','Absent')]
>         [System.String]
>         $Ensure = 'Present'
> ```

This non-mandatory parameter is not used in the function, we should not add non-mandatory functions unless they is required for Get-TargetResource to work.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 93 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScr6Ed00loYrHbSDfZ:-MSk1bxuBkXT6r1pZnnZ:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L93)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $recordHostName = "_$($SymbolicName)._$($Protocol)".ToLower()
> ```

Can we add a blank row before this row?
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 203 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSclK6n6qCFn9IzKluB:-MSk1hdmCvPcL3MTyxD2:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L203)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $Priority=10
> ```

There is no need for a default value on this property since it should only be used when creating a new object (see other comments), so the default value can be set prior to creating the object in the code below.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 207 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSclnc3CvAckVTorUX2:-MSk1i0C14_ytwINewoh:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L207)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $Weight=20
> ```

There is no need for a default value on this property since it should only be used when creating a new object (see other comments), so the default value can be set prior to creating the object in the code below.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 210 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSco_sI8h7Igh1BXGdf:-MSk1yPDErK9oOAmeXiT:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L210)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> TryParse($_, [ref]$ts)
> ```

We should have space after `[ref]`, e.g.  `[ref]$ts`. Throughout the functions.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 210 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScodYE0s3sLHABVvbI:-MSk2rY44XUsbVONmbX4:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L210)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [system.timespan]
> ```

If we change this to PascalCase too tit follows the rest of the types: `[System.TimeSpan]`. Throughout the functions.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 224 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MScmjdD91MP7XPiHBYE:-MSjx5sp8TSwrnVEOXrt:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L224)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $DNSParameters
> ```

We should use camelCase for variables (parameter variables should be PascalCase). Throughout.
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 228 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSckmwWDeHz3qcbCe3S:-MSjxVlS6ypywKuDObu_:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L228)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     $recordHostName = "_$($SymbolicName)._$($Protocol)".ToLower()
> ```

Can we add a blank row before this row?
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 230 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSckcpWDzygYJBWEuee:-MSjwcEv8aL5twusCJKg:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/77316f4527f3471971ae6c9ff9b2bb7b1b1c5285/source/DSCRes [...]

2021-02-07 16:20 UTC, johlju requested changes
Tests look good. Just some minor style comment, and a comment on the tests, then I think this is ready to merge. :slightly_smiling_face:  Awesome work on the integration test. :smiley: 

> Reviewed 1 of 13 files at r1, 1 of 6 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-:-MSxHUmA3irmjJD3HV7R:b-k50how)* status: all files reviewed, 13 unresolved discussions (waiting on @Sudman1)

___
*[.vscode/settings.json, line 41 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSx8Hmi5eQNJQsGEiN5:-MSx8Hmj4xlzicBQlD82:by7wmt6) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/.vscode/settings.json#L41)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     },
>     "editor.rulers": [
>         80,120
>     ]
> ```
</details>


Maybe we should keep this out of the workspace VS Code settings file?  :thinking: Was it a special reason to add this here that could be useful for others? I do have  a ruler myself around 70 chars.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 29 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSx9NaY5qOet7F_Bk1R:-MSx9NaY5qOet7F_Bk1S:b32om8l) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L29)):*
> ```
>     .PARAMETER Priority
>         Specifies the Priority value of the SRV record.
> ```

We should remove these from the comment-based help since they are not a parameter of the Get-function. Also for others that is no longer present.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 260 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBT1p-A2zAqR2UGcY:-MSxBT1p-A2zAqR2UGcZ:b-7daink) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L260)):*
> ```
> if ($PSBoundParameters.ContainsKey('Priority'))
> ```
Can we add blank row before this one?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 264 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBVBo35X2WebUdNc5:-MSxBVBo35X2WebUdNc6:bt4a7ky) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L264)):*
> ```
>  if ($PSBoundParameters.ContainsKey('Weight'))
> ```
Can we add blank row before this one?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 268 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBW_s60FcOCJ9La-T:-MSxBW_s60FcOCJ9La-U:b-qr2bc4) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L268)):*
> ```
> if ($PSBoundParameters.ContainsKey('TTL'))
> ```
Can we add blank row before this one?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 386 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBjdW0Y21u0_ukJjz:-MSxBjdW0Y21u0_ukJk-:b-ua6n09) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L386)):*
> ```
> $result = Get-TargetResource @getTargetResourceParams
> ```
Can we add blank row before this one?
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 395 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBvvq5xBrJgRSNNPO:-MSxBvvq5xBrJgRSNNPP:bp5d1nq) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L395)):*
> ```
> if ($Ensure -eq 'Present')
> ```

Can we add blank row before this one?
___
*[tests/Integration/MSFT_xDnsRecordSrv.config.ps1, line 68 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxD2U9D5SIFSvxi6k9:-MSxD2U9D5SIFSvxi6kA:b-xyv7s3) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.config.ps1#L68)):*
> ```
> Add TTL, Priority, and Weight to an existing SRV record
> ```

Could we add a configuration (integration test) that adds a record using only the mandatory parameters, then use that to change TTL for this configuration? Lets keep the configuration MSFT_xDnsRecordSrv_CreateRecord_Config as that is a good test too creating a record using all parameters.
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 38 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxEF3MB3ZR0Qo8tFY1:-MSxEF3MB3ZR0Qo8tFY2:b-s0ayrd) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L38)):*
> ```PowerShell
>         }
> ```

We can remove one extra blank line here
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 94 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxELSFAXRabsLirUHg:-MSxELSFAXRabsLirUHh:b-b9hrcw) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L94)):*
> ```PowerShell
>         }
> ```

We can remove two extra blank lines here
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 151 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxETtKDjfzom8lSVAV:-MSxETtKDjfzom8lSVAW:b-b9hrcw) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L151)):*
> ```PowerShell
>         }
> ```

We can remove two extra blank lines here
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 210 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxEWC21lxeo2saWGE1:-MSxEWC21lxeo2saWGE2:bos8fcd) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L210)):*
> ```PowerShell
>     }
>     #endregion
> ```

We can remove this blank line here
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 216 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxEa8xECms_Lt3y7ZU:-MSxEa8y4ltYZal2AfFQ:bdke8tz) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L216)):*
> ```
> #region CLEANUP
> #endregion
> ```

We can remove this region-comment block.


<!-- Sent from Reviewable.io -->

2021-02-07 16:34 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130)* status: all files reviewed, 14 unresolved discussions (waiting on @Sudman1)

___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 4 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxKR-cEMokTvTBe_pm:-MSxKR-cEMokTvTBe_pn:bcuz64n) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L4)):*
> ```PowerShell
> $script:dscResourceFriendlyName = 'xDnsRecordSrv'
> $script:dscResourceName = "MSFT_$($script:dscResourceFriendlyName)"
> ```

I see this is not run in the pipeline - it is because the file name should end with `.Integration.Tests.ps1` so Pester is not picking it up. Saw that other tests are not named correctly either so they do not run either, but let's leave the other for now. They might break this PR if they haven't been run. So just rename this file correctly so we can test this resource at least. :smile: 

https://dev.azure.com/dsccommunity/xDnsServer/_build/results?buildId=3813&view=logs&jobId=14d0eb3f-bc66-5450-3353-28256327ad6c&j=14d0eb3f-bc66-5450-3353-28256327ad6c&t=c344f041-83bb-5f7b-1678-8a78f1873256


<!-- Sent from Reviewable.io -->

2021-02-09 13:15 UTC, Sudman1 reviewed
Running through the suggestions, it became apparent that Priority and Weight needed to be mandatory, even though they aren't key attributes. The Add-DnsServerResourceRecord cmdlet requires them to be specified. So I had to refactor a lot of the code to support that. So some of your comments may be overcome by events.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-:-MT5mi6kAsi8AxyzMpDe:b1ixn1a)* status: 5 of 14 files reviewed, 14 unresolved discussions (waiting on @johlju)

___
*[.vscode/settings.json, line 41 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSx8Hmi5eQNJQsGEiN5:-MT5ndEG8gZ2gT34z59E:bd0u1ej) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/.vscode/settings.json#L41)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     },
>     "editor.rulers": [
>         80,120
>     ]
> ```

Maybe we should keep this out of the workspace VS Code settings file?  :thinking: Was it a special reason to add this here that could be useful for others? I do have  a ruler myself around 70 chars.
</blockquote></details>

That was supposed to be a private setting. I've reverted it.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 29 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSx9NaY5qOet7F_Bk1R:-MT5nqOj7E3S7yau_l2v:b-oictc2) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L29)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     .PARAMETER Priority
>         Specifies the Priority value of the SRV record.
> ```

We should remove these from the comment-based help since they are not a parameter of the Get-function. Also for others that is no longer present.
</blockquote></details>

They are now mandatory.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 260 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBT1p-A2zAqR2UGcY:-MT5o90QEKkC-VjTmHzE:b-ipc5b7) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L260)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($PSBoundParameters.ContainsKey('Priority'))
> ```
Can we add blank row before this one?
</blockquote></details>

No more if statement
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 264 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBVBo35X2WebUdNc5:-MT5oCRq5cHKdHsLZ2L0:b-ft4tx9) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L264)):*
> No more if statement
No more if statement
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 268 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBW_s60FcOCJ9La-T:-MT5o_YO4TIj-3EQZoCq:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L268)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($PSBoundParameters.ContainsKey('TTL'))
> ```
Can we add blank row before this one?
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 386 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBjdW0Y21u0_ukJjz:-MT5ocv6ErZCqoPxGg0h:b-djvmvy) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L386)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $result = Get-TargetResource @getTargetResourceParams
> ```
Can we add blank row before this one?
</blockquote></details>

I had kept it together specifically because the preceding hash is being used to splat the command on this line, but I've added the blank at your request.
___
*[source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1, line 395 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxBvvq5xBrJgRSNNPO:-MT5p6_d9lfXiD8qfCta:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L395)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($Ensure -eq 'Present')
> ```

Can we add blank row before this one?
</blockquote></details>

Done.
___
*[tests/Integration/MSFT_xDnsRecordSrv.config.ps1, line 68 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxD2U9D5SIFSvxi6k9:-MT5pKgb8aeKa-1gghxf:b-wiayyo) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.config.ps1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Add TTL, Priority, and Weight to an existing SRV record
> ```

Could we add a configuration (integration test) that adds a record using only the mandatory parameters, then use that to change TTL for this configuration? Lets keep the configuration MSFT_xDnsRecordSrv_CreateRecord_Config as that is a good test too creating a record using all parameters.
</blockquote></details>

The creation test only uses mandatory params. the modification test uses all params
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 4 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxKR-cEMokTvTBe_pm:-MT5pYUHA0sXIxdLNbHJ:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I see this is not run in the pipeline - it is because the file name should end with `.Integration.Tests.ps1` so Pester is not picking it up. Saw that other tests are not named correctly either so they do not run either, but let's leave the other for now. They might break this PR if they haven't been run. So just rename this file correctly so we can test this resource at least. :smile: 

https://dev.azure.com/dsccommunity/xDnsServer/_build/results?buildId=3813&view=logs&jobId=14d0eb3f-bc66-5450-3353-28256327ad6c&j=14d0eb3f-bc66-5450-3353-28256327ad6c&t=c344f041-83bb-5f7b-1678-8a78f1873256
</blockquote></details>

Done.
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 38 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxEF3MB3ZR0Qo8tFY1:-MT5pmki4bY_Y4D_efEF:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L38)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove one extra blank line here
</blockquote></details>

Done.
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 94 at r4](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-MSxELSFAXRabsLirUHg:-MT5ppN06pht2BGy6Bcn:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/b7af072b9c00e9b29f4eceb9ac862c267415f5b3/tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1#L94)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove two extra blank lines here
</blockquote></details>

Done.
___
*[tests/Integration/MSFT_xDnsRecordSrv.Integration.ps1, line 151 at r4](https://reviewable.io/rev [...]

2021-02-09 18:19 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r5, 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/130#-:-MT70JUC1Oy4iKfol8_f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sudman1)



<!-- Sent from Reviewable.io -->

2021-02-09 18:20 UTC, merged

2021-02-09 18:21 UTC, johlju commented
@Sudman1 awesome work on this! 😄 Merged. A preview version should be release shortly.