BREAKING CHANGE: DnsRecordSrv/DnsRecordSrvScoped: Re-implemented as class-based resource
dsccommunity/xDnsServer pull request #201
Opened 2021-03-02 02:00 UTC by Sudman1

#### Pull Request (PR) description

Implements a base class for all record types to use, simplifying what needs to be done to implement all record types and allows for the appropriate implementation of the ZoneScope property by placing it in a record subclass (i.e.: DnsRecordSrvScoped).

#### This Pull Request (PR) fixes the following issues

- Fixes #149

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help. **Does not use schema.mof file. Parameter Descriptions not updated in the README.md, as that has moved to the Wiki.**
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2021-03-02 15:51 UTC, johlju commented
Awesome, looking forward to review this one! 😃  I see there are a lot of conflicts in files, can you rebase it when you have chance.

I will review as soon as I have time.

2021-03-13 11:53 UTC, johlju commented
___
*[tests/Unit/Classes/DnsRecordBase.tests.ps1, line 125 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfQk0P9xk3Fnl2SAzY:-MVfQk0P9xk3Fnl2SAzZ:b-b8jpz6) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Classes/DnsRecordBase.tests.ps1#L125)):*
> ```PowerShell
>                     }
>                 }
>                 $script:instanceDesiredState = [MockRecordDoesNotExist] @{
> ```

We should have a blank row before this row.


<!-- Sent from Reviewable.io -->

2021-03-13 11:59 UTC, johlju requested changes
I have review the DnsRecordBase. Awesome work @sudman1! :smiley:  Would be great to get these changes in before I review the rest of this PR, I think it will help me not needing to comment on the things that you fix with these comments I made today. :slightly_smiling_face: 

> Reviewed 15 of 34 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-:-MVfRPtuB1oSckf-jJrn:bm8tc4e)* status: 18 of 34 files reviewed, 61 unresolved discussions (waiting on @Sudman1)

___
*[CHANGELOG.md, line 32 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVer0YV-tqajihuNeJx:-MVer0YW-t3MpZQILy5B:b-xgcez7) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/ec75a94e1d96fd3f78bc8adc2e1301a0e239038a/CHANGELOG.md#L32)):*
> ```
> - xDnsRecordSrv
>   - Added new resource to manage SRV records
> ```

I suggest we keep this in the change log as there is a resource added, but change to the name to `DnsRecordSrv`, and add `DnsRecordSrvScoped`. Also see next comment.
___
*[CHANGELOG.md, line 48 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVerO0J11h2r95jjYgh:-MVerO0J11h2r95jjYgi:b-fuigwo) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/CHANGELOG.md#L48)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> - Class-based Resource records
>   - DnsRecordBase (base record resource class)
>   - DnsRecordSrv
>   - DnsRecordSrvScoped
> ```
</details>


Suggest changing the above to something like (see also previous comment):

```
- xDnsServer
  - Added a class `DnsRecordBase` that is used as the base class for the resources that create DNS records.
```

___
*[source/xDnsServer.psd1, line 21 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVerzoA-myrLNzCbvzq:-MVerzoA-myrLNzCbvzr:b15ifo) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/xDnsServer.psd1#L21)):*
> ```
> PowerShellVersion = '5.0'
> ```

We should add this to the change lgo that we are changing the minimum required PS version to 5.0. This is a breaking change so we should add `BREAKING CHANGE: ` to the entry in the change log as well.
___
*[source/Classes/001.DnsRecordBase.ps1, line 4 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVesY_EBRYrYpsrPNls:-MVesY_EBRYrYpsrPNlt:b84jpwu) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L4)):*
> ```
> .PARAMETER ZoneName
> ```

We should add a blank line before this line. Throughout for all `.PARAMETER` lines.
___
*[source/Classes/001.DnsRecordBase.ps1, line 14 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVf7k8k0MzqT4n55Jfo:-MVf7k8k0MzqT4n55Jfp:b-2ikadz) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L14)):*
> ```
> en-US
> ```

Suggest we surround this with single-quote `'en-US'`. Throughout all files.
___
*[source/Classes/001.DnsRecordBase.ps1, line 19 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVet4xN5OQixvo9Fn59:-MVet4xN5OQixvo9Fn5A:b-2njb7n) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L19)):*
> ```
>     [DscProperty(Key)]
>     [string] $ZoneName
> ```

I think we should have it like the following to align with the rest of the DSC resources (here and all other MOF resources in other modules). Throughout all propertyes

Full type name and the parameter variable name on a separate row.
```
[DscProperty(Key)]
[System.String] 
$ZoneName
```

I will try to add this to the style guideline soon. We have nothing around class-based resources there yet.
___
*[source/Classes/001.DnsRecordBase.ps1, line 31 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeuCLAAAmGxEWIIN5G:-MVeuCLBCeA2wXa-JA8S:bmzy27) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L31)):*
> ```
> $isScoped
> ```

Discussing: Since we don't have a style guideline around this we need to add rules around this too. :slightly_smiling_face:  So normally properties should have PascalCase, but since this is a hidden (private) property is it your thought that we should have these as camelCase to indicate that it is a private property? What is your thought around this?
___
*[source/Classes/001.DnsRecordBase.ps1, line 46 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVevaDj302YDPI0Nykt:-MVevaDj302YDPI0Nyku:bd8spis) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L46)):*
> ```
>         $record = $this.GetResourceRecord()
>         $dscResourceObject = $null
> ```

Minor: I would have like to see these switch place, with a blank row in between. More logical when the if() comes next.

```
         $dscResourceObject = $null

         $record = $this.GetResourceRecord()
```
___
*[source/Classes/001.DnsRecordBase.ps1, line 56 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVewSPB7jwtjSGrjWDY:-MVewSPB7jwtjSGrjWDZ:bn596th) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L56)):*
> ```
> [activator]
> ```

Suggest using the full type name `[System.Activator]`.
___
*[source/Classes/001.DnsRecordBase.ps1, line 57 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVewfEn8v6dKYSfyMm_:-MVewfEn8v6dKYSfyMma:bays6i5) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L57)):*
> ```
> foreach ($propertyName in $this.PSObject.Properties.Name)
> ```

We should add blank line before this to separate the logic and get some air in the code.
___
*[source/Classes/001.DnsRecordBase.ps1, line 61 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVewrFSBrDJ9Zr19nO1:-MVewrFSBrDJ9Zr19nO2:byf6oyg) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L61)):*
> ```
> $dscResourceObject.Ensure = 'Absent'
> ```

We should add blank line before this to separate the logic and get some air in the code.
___
*[source/Classes/001.DnsRecordBase.ps1, line 70 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVex5r2AKX1MYcTp47M:-MVex5r2AKX1MYcTp47N:b-p7l2ws) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L70)):*
> ```
> return $dscResourceObject
> ```

We should add blank line before this to separate the logic and get some air in the code.
___
*[source/Classes/001.DnsRecordBase.ps1, line 84 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVexDLJCFw6tDYzKcN3:-MVexDLJCFw6tDYzKcN4:bk8lcfy) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L84)):*
> ```
> Where-Object {
> ```

We should use named parameter `Where-Object -FilterScript { ... }`
___
*[source/Classes/001.DnsRecordBase.ps1, line 95 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeyuzS20NKWi8eY5A4:-MVeyuzS20NKWi8eY5A5:b-xnlswp) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L95)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             if ($null -ne $existingRecord)
>             {
>                 Write-Verbose -Message $script:localizedDataDnsRecordBase.RemovingExisitngRecord
>                 # Removing existing record (required for [...]

2021-03-13 12:00 UTC, johlju commented
@Sudman1 most comment are just style comments. Again, awesome work. I will continue review when you pushed these changes.

2021-03-14 03:00 UTC, Sudman1 reviewed
As I'm going through these comments, it strikes me that most of these discrepancies come directly from the Sampler ClassResource template I used to create this resource. As you know, I've made my own template which required modifying plaster. So I will update those as I go to (hopefully) address these in future DnsRecord PRs.

However, I suggest a thorough review of the Sampler templates (or at least their file output) to keep folks from making the same changes every time they use said templates.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-:-MViG-3n0DcQmY2oHetv:bhvg3gp)* status: 18 of 34 files reviewed, 60 unresolved discussions (waiting on @johlju)

___
*[CHANGELOG.md, line 32 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVer0YV-tqajihuNeJx:-MVi8mj7E7dZxTiHRnbz:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/ec75a94e1d96fd3f78bc8adc2e1301a0e239038a/CHANGELOG.md#L32)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> - xDnsRecordSrv
>   - Added new resource to manage SRV records
> ```

I suggest we keep this in the change log as there is a resource added, but change to the name to `DnsRecordSrv`, and add `DnsRecordSrvScoped`. Also see next comment.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 48 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVerO0J11h2r95jjYgh:-MVi8nmQ4VDaIwGtXjIy:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/CHANGELOG.md#L48)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> - Class-based Resource records
>   - DnsRecordBase (base record resource class)
>   - DnsRecordSrv
>   - DnsRecordSrvScoped
> ```

Suggest changing the above to something like (see also previous comment):

```
- xDnsServer
  - Added a class `DnsRecordBase` that is used as the base class for the resources that create DNS records.
</blockquote></details>

Done.
___
*[source/xDnsServer.psd1, line 21 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVerzoA-myrLNzCbvzq:-MVi9Y8f1YNM8ASYPp3e:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/xDnsServer.psd1#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> PowerShellVersion = '5.0'
> ```

We should add this to the change lgo that we are changing the minimum required PS version to 5.0. This is a breaking change so we should add `BREAKING CHANGE: ` to the entry in the change log as well.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 4 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVesY_EBRYrYpsrPNls:-MViBhYrCmMFDUmBNwQ_:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> .PARAMETER ZoneName
> ```

We should add a blank line before this line. Throughout for all `.PARAMETER` lines.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 14 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVf7k8k0MzqT4n55Jfo:-MViCP4i8vq60v4YKU2D:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> en-US
> ```

Suggest we surround this with single-quote `'en-US'`. Throughout all files.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 19 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVet4xN5OQixvo9Fn59:-MViHt4G-lLUe6H3rJg_:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L19)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>     [DscProperty(Key)]
>     [string] $ZoneName
> ```

I think we should have it like the following to align with the rest of the DSC resources (here and all other MOF resources in other modules). Throughout all propertyes

Full type name and the parameter variable name on a separate row.
```
[DscProperty(Key)]
[System.String] 
$ZoneName
```

I will try to add this to the style guideline soon. We have nothing around class-based resources there yet.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 31 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeuCLAAAmGxEWIIN5G:-MViHxuF4kbSqapa5Wq6:b1pxzww) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L31)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $isScoped
> ```

Discussing: Since we don't have a style guideline around this we need to add rules around this too. :slightly_smiling_face:  So normally properties should have PascalCase, but since this is a hidden (private) property is it your thought that we should have these as camelCase to indicate that it is a private property? What is your thought around this?
</blockquote></details>

You are correct. My thought is that if a property is private, that camelCase would be the more appropriate style for it. This especially rang true for me since end-users do not interact with this property at all.
___
*[source/Classes/001.DnsRecordBase.ps1, line 56 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVewSPB7jwtjSGrjWDY:-MViLtx-21yUMpRFydoT:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L56)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [activator]
> ```

Suggest using the full type name `[System.Activator]`.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 57 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVewfEn8v6dKYSfyMm_:-MViLzfC-Xhs2G7LkYLe:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L57)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> foreach ($propertyName in $this.PSObject.Properties.Name)
> ```

We should add blank line before this to separate the logic and get some air in the code.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 61 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVewrFSBrDJ9Zr19nO1:-MViM2wEEmdEuo0HMC3O:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $dscResourceObject.Ensure = 'Absent'
> ```

We should add blank line before this to separate the logic and get some air in the code.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 70 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVex5r2AKX1MYcTp47M:-MViM60g1OZHF4-reliB:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> return $dscResourceObject
> ```

We should add blank line before this to separate the logic and get some air in the code.
</blockquote></details>

Done.
___
*[source/Cla [...]

2021-03-14 04:22 UTC, Sudman1 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 11 of 41 files reviewed, 60 unresolved discussions (waiting on @johlju)

___
*[tests/Unit/Stubs/DnsServer.psm1, line 5662 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfNvqC3sTYOO4f9aOc:-MVixkLT9NrNiU3tTvMi:bwualky) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Stubs/DnsServer.psm1#L5662)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This broke a unit test in the Mx resource, so I have changed `throw` to `Write-Verbose`. We can probably change this back once Mx falls under the DnsRecordBase class.


<!-- Sent from Reviewable.io -->

2021-03-14 08:33 UTC, johlju commented
> However, I suggest a thorough review of the Sampler templates (or at least their file output) to keep folks from making the same changes every time they use said templates.

I haven't seen (reviewed) or used those templates in Sampler so did not know they did not follow DSC Community style guideline. I will add an issue to track that, if they can be changed to follow DSC Community style guideline. 🙂

2021-03-14 09:28 UTC, johlju requested changes
> Reviewed 13 of 18 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 25 of 41 files reviewed, 7 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 31 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeuCLAAAmGxEWIIN5G:-MVjtkMs1QQNgYi-XU2V:b1x6vc9) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L31)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

You are correct. My thought is that if a property is private, that camelCase would be the more appropriate style for it. This especially rang true for me since end-users do not interact with this property at all.
</blockquote></details>

Sounds good to me. :slightly_smiling_face:  Created issue https://github.com/dsccommunity/dsccommunity.org/issues/168 to track new guideline rules.
___
*[source/Classes/001.DnsRecordBase.ps1, line 95 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeyuzS20NKWi8eY5A4:-MVjuT3Q7wySpa1QE9t0:bm5fo2x) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L95)):*
> this is done in case we ever want to support the AgeRecord parameter

Then I think we should only do this when `AgeRecord` is enforced.

> I submit that if it is not specified, then the user would expect an optional value such as TimeToLive to be defaulted, not kept as it may have been previously set.

A DSC resource should not change a value that is not enforced. A user should be able to set TTL manually and not enforce it through the DSC configuration, then the DSC resource should not remove that manually set value. If the user want to enforce the value to the default value that value must be specified in the configuration.
___
*[source/Classes/001.DnsRecordBase.ps1, line 132 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVf0FQp22P9PRK_NE9U:-MVjvc9J0-59xKQv6iNR:bwyaa2e) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L132)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Those functions seem as though they may be useful. However, they are written to work with hash tables and not objects and there is no comment-based help/real-world examples to make me comfortable with their usage.

As my logic works, I'm inclined to keep it as-is for now and leave that possibility to someone else or possibly revisit it in the future when I have had more experience with the DscResource.Common module.
</blockquote></details>

Since the `$currentState` and `$desiredState` was convert to hashtable I expected it to be easy to just replace the foreach with this function. But I'm good with changing this later. Could you create an issue  to track this?
___
*[source/Classes/001.DnsRecordBase.ps1, line 42 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVju01UDlrPxvaaDJLX:-MVju01UDlrPxvaaDJLY:b12o9pw) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/001.DnsRecordBase.ps1#L42)):*
> ```
> [bool]
> ```

We should use `[System.Boolean]`.
___
*[source/en-US/DnsRecordBase.strings.psd1, line 13 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVjwSby4mpfR_rRD7eh:-MVjwSby4mpfR_rRD7ei:b-48owrg) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordBase.strings.psd1#L13)):*
> ```
> '{2}.'
> ```

We should have the full stop after the single-quote: `'{2}'.`
___
*[source/Private/ConvertTo-HashtableFromObject.ps1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfLfq-1JZvdr8lqBms:-MVjwxSwDIbtQ7CEzmRo:b-frguc6) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Private/ConvertTo-HashtableFromObject.ps1#L8)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

It's worth talking to Gael about this. This file comes straight from Sampler as-is.
</blockquote></details>

Since this is a just template function we can always change it, but I think this function should be in DscResource.Common and not part of the template, as it will be unnecessarily duplicated throughout a lot of repos. We keep it as is for now. I added an issue to Sampler to track it.
___
*[tests/Unit/Classes/DnsRecordBase.tests.ps1, line 68 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfPdmT7ZVRpwCbSEgr:-MVjzT04CWxFt5i6yR0Y:bngpql6) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Classes/DnsRecordBase.tests.ps1#L68)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Trying to get an empty response. $null is not an appropriate value. Changed to `return {}`
</blockquote></details>

But doesn't this also returns null? `$null -eq (Invoke-Command {}` returns $true. But this looks better at least so lets leave it. :slightly_smiling_face: 
___
*[tests/Unit/Private/ConvertTo-HashtableFromObject.tests.ps1, line 43 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfIWyIAATeU2Ll2TE-:-MVk11Me-ZHDdEYYT6Mp:b-z3xrcc) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Private/ConvertTo-HashtableFromObject.tests.ps1#L43)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Done. This will need to be addressed in Sampler.
</blockquote></details>

Tracking this in issue https://github.com/gaelcolas/Sampler/issues/245 for Sampler.
___
*[tests/Unit/Stubs/DnsServer.psm1, line 5662 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfNvqC3sTYOO4f9aOc:-MVk1tsbD5Hz0jrPef_n:bhcn9kr) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Stubs/DnsServer.psm1#L5662)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

This broke a unit test in the Mx resource, so I have changed `throw` to `Write-Verbose`. We can probably change this back once Mx falls under the DnsRecordBase class.
</blockquote></details>

Probably a mock that is missing. Can you please add an issue to track this, so we can fix this in a separate PR?


<!-- Sent from Reviewable.io -->

2021-03-14 09:35 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 25 of 41 files reviewed, 7 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 95 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeyuzS20NKWi8eY5A4:-MVk4_ZJ6X7oDkhEUX0V:b-ubr50p) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> this is done in case we ever want to support the AgeRecord parameter

Then I think we should only do this when `AgeRecord` is enforced.

> I submit that if it is not specified, then the user would expect an optional value such as TimeToLive to be defaulted, not kept as it may have been previously set.

A DSC resource should not change a value that is not enforced. A user should be able to set TTL manually and not enforce it through the DSC configuration, then the DSC resource should not remove that manually set value. If the user want to enforce the value to the default value that value must be specified in the configuration.
</blockquote></details>

In the case of `AgeRecord` I think we should add a `Force` parameter to so that users need to opt-in to having the record removed, so they know that any manually set properties will be removed.


<!-- Sent from Reviewable.io -->

2021-03-14 10:12 UTC, johlju requested changes
> Reviewed 5 of 34 files at r1, 2 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 32 of 41 files reviewed, 22 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/002.DnsRecordSrv.ps1, line 26 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk5n2eDpC8qCcyduTO:-MVk5n2eDpC8qCcyduTP:b-c8htmo) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L26)):*
> ```
> ZoneName
> ```

We should remove this as it not part of this class. The auto-doc should get these from the base class (it is tracked in https://github.com/dsccommunity/DscResource.DocGenerator/issues/62).
___
*[source/Classes/002.DnsRecordSrv.ps1, line 29 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk6ATqDFm00C9GJJxS:-MVk6ATqDFm00C9GJJxT:bh604hg) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L29)):*
> ```
> TimeToLive
> ```

We should remove this as it not part of this class. 
___
*[source/Classes/002.DnsRecordSrv.ps1, line 32 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk6Bc2-fJAMIJRMV5R:-MVk6Bc34GfEuzxncZlz:br4hphi) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L32)):*
> ```
> DnsServer
> ```

We should remove this as it not part of this class. 
___
*[source/Classes/002.DnsRecordSrv.ps1, line 35 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk6FS1691tw-gCYdOt:-MVk6FS1691tw-gCYdOu:bsveloe) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L35)):*
> ```
> Ensure
> ```

We should remove this as it not part of this class. 
___
*[source/Classes/002.DnsRecordSrv.ps1, line 94 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk8_sA5OlX2fxD2ncj:-MVk8_sA5OlX2fxD2nck:b-o4ha21) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L94)):*
> ```
> $this.ZoneScope
> ```

This property does not exist for DnsRecordSrv. I think DnsRecordSrvScope should have it's own Verbose message, even if that means we need to add more logic to the method in DnsRecordSrvScope. If you feel you need to duplicate logic, then I suggest to add helper functions. See next comment as well.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 103 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk7hk02k-QMSGb5rel:-MVk7hk02k-QMSGb5rem:bgecuzj) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L103)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         if ($this.isScoped)
>         {
>             $dnsParameters['ZoneScope'] = $this.ZoneScope
>         }
> ```
</details>


I think we should move all code that is handling ZoneScope to the class DnsRecordSrvScoped, it can be set in the object returned from the inherited class method? More logical to me than referencing to a property that is not in this class (or in some cases in parent class). 
___
*[source/Classes/002.DnsRecordSrv.ps1, line 151 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkBBLO9BtzoeV63_R4:-MVkBBLO9BtzoeV63_R5:b-gqpeen) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L151)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         if ($this.isScoped)
>         {
>             $dnsParameters['ZoneScope'] = $this.ZoneScope
>         }
> ```
</details>


Same comment as above. Suggest moving to class DnsRecordSrvScoped
___
*[source/Classes/003.DnsRecordSrvScoped.ps1, line 9 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkBVxu0KI_oMyY255G:-MVkBVxu0KI_oMyY255H:b-1itkv2) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/003.DnsRecordSrvScoped.ps1#L9)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
>     .PARAMETER SymbolicName
>         Service name for the SRV record. eg: xmpp, ldap, etc. (Key Parameter)
>     .PARAMETER Protocol
>         Service transmission protocol ('TCP' or 'UDP') (Key Parameter)
>     .PARAMETER Port
>         The TCP or UDP port on which the service is found (Key Parameter)
>     .PARAMETER Target
>         Specifies the Target Hostname or IP Address. (Key Parameter)
>     .PARAMETER Priority
>         Specifies the Priority value of the SRV record. (Mandatory Parameter)
>     .PARAMETER Weight
>         Specifies the weight of the SRV record. (Mandatory Parameter)
>     .PARAMETER ZoneName
>         Specifies the name of a DNS zone. (Key Parameter)
>     .PARAMETER ZoneScope
>         Specifies the name of a zone scope. (Key Parameter)
>     .PARAMETER TimeToLive
>         Specifies the TimeToLive value of the SRV record. Value must be in valid TimeSpan string format (i.e.: Days.Hours:Minutes:Seconds.Miliseconds or 30.23:59:59.999).
>     .PARAMETER DnsServer
>         Name of the DnsServer to create the record on.
>     .PARAMETER Ensure
>         Whether the host record should be present or removed.
> ```
</details>


We should only leave `ZoneScope` as it is the only property in this class. Auto-doc should recursively find all properties.
___
*[source/Classes/003.DnsRecordSrvScoped.ps1, line 53 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkAVKuEz20S9o-4xHB:-MVkAVKv23rPmxKjLrvd:b-byv02l) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/003.DnsRecordSrvScoped.ps1#L53)):*
> ```
> [DnsRecordBase]
> ```

Should it be [DnsRecordSrv] instead since it is the inherited class? Not sure though. :slightly_smiling_face: 
Same for the others below?
___
*[source/en-US/DnsRecordSrv.strings.psd1, line 8 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkClKZ4AuIRtkACqX_:-MVkClKZ4AuIRtkACqXa:b-mbkb9o) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrv.strings.psd1#L8)):*
> ```
> from '{5}'
> ```

We should have a full stop `.` at the end.
___
*[source/en-US/DnsRecordSrv.strings.psd1, line 8 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkCntGBaDWa6lSb3SN:-MVkCntGBaDWa6lSb3SO:b-84mef) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrv.strings.psd1#L8)):*
> ```
> with the '{4}' scope
> ```

Should not mentioned scope since the resource does not have scope. This should instead be outputted by the resource DnsRecordSrvScoped from its localization string file.
___
*[source/en-US/DnsRecordSrv.strings.psd1, line 9 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkD7o08YxDVuHKpgfd:-MVkD7o08YxDVuHKpgfe:b-84mef) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrv.strings.psd1#L9)):*
> ```
> with the '{4}' scope
> ```

Should not mentioned scope since the resource does not have scope. This should instead be outputted by the resource DnsRecordSrvScoped from its localization string file.
___
*[source/en-US/DnsRecordSrvScoped.strings.psd1, line 8 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkC54E-roAZ2WUBtl9:-MVkC54E-roAZ2WUBtlA:bu92y1a) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrvScoped.strings.psd1#L8)):*
> ```
> GettingDnsRecordMessage
> ```

This is not used, see other comments that we should use this.
___
 [...]

2021-03-14 10:13 UTC, johlju commented
I only have the tests left to review after this, but wait to review them until we resolved the current review comments. 🙂

2021-03-14 15:14 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 32 of 41 files reviewed, 22 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 132 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVf0FQp22P9PRK_NE9U:-MVlHyKd6QB896NcP-8H:b-ivl3mj) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L132)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Since the `$currentState` and `$desiredState` was convert to hashtable I expected it to be easy to just replace the foreach with this function. But I'm good with changing this later. Could you create an issue  to track this?
</blockquote></details>

@sudman1 I added a PR in your fork here https://github.com/Sudman1/xDnsServer/pull/2 that should resolve this. Merge it if you want to use it. It also adds a few unit tests.


<!-- Sent from Reviewable.io -->

2021-03-14 15:18 UTC, Sudman1 commented
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)_ status: 32 of 41 files reviewed, 22 unresolved discussions (waiting on @Sudman1)
> 
> _[source/Classes/001.DnsRecordBase.ps1, line 132 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVf0FQp22P9PRK_NE9U:-MVlHyKd6QB896NcP-8H:b-ivl3mj) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L132)):_
> 
> Previously, johlju (Johan Ljunggren) wrote…
> @Sudman1 I added a PR in your fork here [Sudman1#2](https://github.com/Sudman1/xDnsServer/pull/2) that should resolve this. Merge it if you want to use it. It also adds a few unit tests.

That's awesome! I'll take a look this evening when I'm able to get back onto my system.

2021-03-14 17:59 UTC, johlju requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 31 of 41 files reviewed, 22 unresolved discussions (waiting on @johlju and @Sudman1)

___
*[tests/Unit/Classes/DnsRecordBase.tests.ps1, line 172 at r6](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVlsu2S-StAnGIpdFnE:-MVlsu2T-_EReBb2Sxnr:b-kybhvi) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/46a5bf92098ca85d0ba8a5ccd48b72d85a8e5e01/tests/Unit/Classes/DnsRecordBase.tests.ps1#L172)):*
> ```
> ...system is not in...
> ```

I missed this in my PR to yours. Here it should have said '...system is in...' (removing 'not')


<!-- Sent from Reviewable.io -->

2021-03-15 03:39 UTC, Sudman1 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 25 of 41 files reviewed, 22 unresolved discussions (waiting on @johlju)

___
*[source/Classes/001.DnsRecordBase.ps1, line 95 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVeyuzS20NKWi8eY5A4:-MVnARrgBXjzG-pYAeee:b-pzd9ky) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/source/Classes/001.DnsRecordBase.ps1#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

In the case of `AgeRecord` I think we should add a `Force` parameter to so that users need to opt-in to having the record removed, so they know that any manually set properties will be removed.
</blockquote></details>

Okay. I'm not even convinced that AgeRecord should really ever be supported anyway, so I'll just go with the Set-DnsResourceRecord route.

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 42 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVju01UDlrPxvaaDJLX:-MVkA4Ga-A82Wc63DJfr:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/001.DnsRecordBase.ps1#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [bool]
> ```

We should use `[System.Boolean]`.
</blockquote></details>

Done.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 26 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk5n2eDpC8qCcyduTO:-MVnA7zf6-4tOUVQDniB:bcje4vk) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> ZoneName
> ```

We should remove this as it not part of this class. The auto-doc should get these from the base class (it is tracked in https://github.com/dsccommunity/DscResource.DocGenerator/issues/62).
</blockquote></details>

Alright. Didn't know that was possible.

Done.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 29 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk6ATqDFm00C9GJJxS:-MVni6Bn804HzF-qCPs_:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L29)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> TimeToLive
> ```

We should remove this as it not part of this class. 
</blockquote></details>

Done.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 32 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk6Bc2-fJAMIJRMV5R:-MVni6raA7oFn9G4ooxJ:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L32)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> DnsServer
> ```

We should remove this as it not part of this class. 
</blockquote></details>

Done.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 35 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk6FS1691tw-gCYdOt:-MVni7ZE9xJDJJFLOmNe:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L35)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Ensure
> ```

We should remove this as it not part of this class. 
</blockquote></details>

Done.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 94 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk8_sA5OlX2fxD2ncj:-MVniGm99qcr0JAxFRvB:bc1a0ij) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L94)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $this.ZoneScope
> ```

This property does not exist for DnsRecordSrv. I think DnsRecordSrvScope should have it's own Verbose message, even if that means we need to add more logic to the method in DnsRecordSrvScope. If you feel you need to duplicate logic, then I suggest to add helper functions. See next comment as well.
</blockquote></details>

This equates to more than just adding logic to the Scoped instance. The logic for the two classes is identical. the only difference is the ZoneScope which, in my design, gets splatted away in the underlying functions. This effectively makes the parent class method the helper function.

With this design, the scoped subclass does not need to implement *any* logic at all. All it needs to do is declare the $ZoneScope as a Key parameter and define the object's signature - which is just a copy/paste from the parent + the ZoneScope property.

Bottom line is that I believe this design makes it easier for the developer to write the scoped class. If the logic works in the parent class, it will just work in the child class as well.

As pertains specifically to the verbose message here, there are two ways I see to address this while keeping all the logic in the parent class:

1. Leave it as is since there is essentially an implied empty zone scope
2. Just modify the localized strings for the parent class so that zone scope information is not included in the verbose string output.

I'd much prefer going with option 2 than killing the entire inheritance design.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 103 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk7hk02k-QMSGb5rel:-MVnme9MCFnFiSkgJnS4:bmwbsl8) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L103)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         if ($this.isScoped)
>         {
>             $dnsParameters['ZoneScope'] = $this.ZoneScope
>         }
> ```

I think we should move all code that is handling ZoneScope to the class DnsRecordSrvScoped, it can be set in the object returned from the inherited class method? More logical to me than referencing to a property that is not in this class (or in some cases in parent class). 
</blockquote></details>

See previous comment.

But to add to it: The methods which need to be overridden in this design (GetResourceRecord, AddResourceRecord, NewDscResourceObjectFromRecord, and now ModifyResourceRecord) actually perform the work of talking to the DNS server. If the child class were to hold the code handling ZoneScope, it would still need to pass that information to the parent in the form of a parameter which would have to be checked for in the same way as it is now - or we would end up duplicating code in the child, which is no good if any changes are needed in the future.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 151 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkBBLO9BtzoeV63_R4:-MVnp98-3_30zfZB2xhO:bighjnt) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L151)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>         if ($this.isScoped)
>         {
>             $dnsParameters['ZoneScope'] = $this.ZoneScope
>         }
> ```

Same comment as above. Suggest moving to class DnsRecordSrvScoped
</blockquote></details>

See previous
___
*[source/Classes/003.DnsRecordSrvScoped.ps1, line 9 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkBVxu0KI_oMyY255G:-MVnpCch6IVy5XIxyGHQ:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/003.DnsRecordSrvScoped.ps1#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) [...]

2021-03-15 16:49 UTC, johlju requested changes
> Reviewed 7 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 32 of 41 files reviewed, 7 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 102 at r7](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVqjDQ_2_zZNaJ4Rjak:-MVqjDQ_2_zZNaJ4Rjal:b-4o11q4) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/30b7e8e7f9215cdba8483807c2e3c5ac6ae5d3dc/source/Classes/001.DnsRecordBase.ps1#L102)):*
> ```
> $existingRecord = $this.GetResourceRecord()
> ```

I wonder if we can skip this and call Get() directly, like Test() does? :thinking: I just saw that this might not be necessary any longer, but I could be mistaken. :slightly_smiling_face: 
___
*[source/Classes/002.DnsRecordSrv.ps1, line 26 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk5n2eDpC8qCcyduTO:-MVqjp970N4FW9Vf03dk:bo3yzkt) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L26)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Alright. Didn't know that was possible.

Done.
</blockquote></details>

I will get on fixing that issue in DocGenerator as soon as I have  chance so we get Auto-Doc working with inherited classes.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 94 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk8_sA5OlX2fxD2ncj:-MVqkAoU-1iAe1Y99LTK:b-9q9fde) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L94)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

This equates to more than just adding logic to the Scoped instance. The logic for the two classes is identical. the only difference is the ZoneScope which, in my design, gets splatted away in the underlying functions. This effectively makes the parent class method the helper function.

With this design, the scoped subclass does not need to implement *any* logic at all. All it needs to do is declare the $ZoneScope as a Key parameter and define the object's signature - which is just a copy/paste from the parent + the ZoneScope property.

Bottom line is that I believe this design makes it easier for the developer to write the scoped class. If the logic works in the parent class, it will just work in the child class as well.

As pertains specifically to the verbose message here, there are two ways I see to address this while keeping all the logic in the parent class:

1. Leave it as is since there is essentially an implied empty zone scope
2. Just modify the localized strings for the parent class so that zone scope information is not included in the verbose string output.

I'd much prefer going with option 2 than killing the entire inheritance design.
</blockquote></details>

Let's go with option 2 then. :slightly_smiling_face:  Thank you for the detailed run down! :smiley: 
___
*[source/Classes/002.DnsRecordSrv.ps1, line 184 at r7](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVqkh7h9X8r0F1pzpkd:-MVqkh7h9X8r0F1pzpke:b-y5bhsj) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/30b7e8e7f9215cdba8483807c2e3c5ac6ae5d3dc/source/Classes/002.DnsRecordSrv.ps1#L184)):*
> ```
> 'Weight'
> ```

Can we add blank row before this one.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 188 at r7](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVqkmJK2cal-VOl--C5:-MVqkmJK2cal-VOl--C6:b-ds6iaf) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/30b7e8e7f9215cdba8483807c2e3c5ac6ae5d3dc/source/Classes/002.DnsRecordSrv.ps1#L188)):*
> ```
> 'TimeToLive'
> ```

Can we add blank row before this one.
___
*[source/Classes/003.DnsRecordSrvScoped.ps1, line 53 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkAVKuEz20S9o-4xHB:-MVqkyOaDYn0-XfuwpDs:b-gzgjbd) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/003.DnsRecordSrvScoped.ps1#L53)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

The parent class just calls the base class anyway. The only reason this is included at all is to pass the HQRM tests, since they require Get(), Set(), and Test() to be explicitly defined in any resource classes. But if they weren't defined, the system would implicitly call the base class' implementations of these methods, so I just do it explicitly.
</blockquote></details>

Thank you for the explanation.
___
*[source/en-US/DnsRecordSrv.strings.psd1, line 8 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkCntGBaDWa6lSb3SN:-MVqlOan-VpFk0iiqd54:b-x0mk39) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrv.strings.psd1#L8)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

See the previous comment with rationale and 2 ways to address.
</blockquote></details>

We'll go with your suggested option 2.
___
*[source/en-US/DnsRecordSrvScoped.strings.psd1, line 8 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkC54E-roAZ2WUBtl9:-MVqlStgEg8fIt3m50OY:b-x0mk39) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrvScoped.strings.psd1#L8)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

You are correct. The intent was that this would be used when the base class calls this class' GetResourceRecord() method (which is inherited by the parent class). But the parent implementation is expressly calling its own localization file - which currently provides the same output, but the logic would need to change if we go with option 2 from my previous comment.
</blockquote></details>

We'll go with your suggested option 2.
___
*[tests/Unit/Classes/DnsRecordBase.tests.ps1, line 68 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfPdmT7ZVRpwCbSEgr:-MVqljov0GxVSde-FTlY:b-pyhwss) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Classes/DnsRecordBase.tests.ps1#L68)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

If I return $null, it doesn't behave the same as an empty response.

See [Empty Null](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-null?view=powershell-7.1#empty-null) on Microsoft docs
</blockquote></details>

Ah, I see we are returning the same as `[void]` does. Learned something new today. :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2021-03-15 16:50 UTC, johlju commented
I will review the last (test) files tomorrow.

2021-03-15 20:01 UTC, Sudman1 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 32 of 41 files reviewed, 7 unresolved discussions (waiting on @johlju and @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 102 at r7](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVqjDQ_2_zZNaJ4Rjak:-MVrJ9Sl4UD5Ig08FSf_:bmktybu) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/30b7e8e7f9215cdba8483807c2e3c5ac6ae5d3dc/source/Classes/001.DnsRecordBase.ps1#L102)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $existingRecord = $this.GetResourceRecord()
> ```

I wonder if we can skip this and call Get() directly, like Test() does? :thinking: I just saw that this might not be necessary any longer, but I could be mistaken. :slightly_smiling_face: 
</blockquote></details>

No - this is a point of confusion in naming. This method gets a CIM instance representing a **DNS** Resource **Record**. Whereas `Get()` returns an Object representing a **DSC** Resource.

The line is still needed. $existingRecord is used in the conditionals below and is passed as an argument to the `ModifyResourceRecord` method.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 94 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk8_sA5OlX2fxD2ncj:-MVrK1Kk0jh_Gu3wxxcA:b-tj9vwv) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L94)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's go with option 2 then. :slightly_smiling_face:  Thank you for the detailed run down! :smiley: 
</blockquote></details>

What would you say to creating a non-DSC method to get the localized data instead of simply saving it in variables? It would make getting the strings easier, would unclutter the resulting psm1 file (not that it matters so much) and would add a bit of complexity to the DnsRecordBase class, but I feel like it would be a cleaner implementation.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 184 at r7](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVqkh7h9X8r0F1pzpkd:-MVrQojDEz-n7N6yuwjk:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/30b7e8e7f9215cdba8483807c2e3c5ac6ae5d3dc/source/Classes/002.DnsRecordSrv.ps1#L184)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'Weight'
> ```

Can we add blank row before this one.
</blockquote></details>

Done.
___
*[source/Classes/002.DnsRecordSrv.ps1, line 188 at r7](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVqkmJK2cal-VOl--C5:-MVrQpLD9T-9QbMPHK3e:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/30b7e8e7f9215cdba8483807c2e3c5ac6ae5d3dc/source/Classes/002.DnsRecordSrv.ps1#L188)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'TimeToLive'
> ```

Can we add blank row before this one.
</blockquote></details>

Done.
___
*[tests/Unit/Classes/DnsRecordBase.tests.ps1, line 68 at r3](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVfPdmT7ZVRpwCbSEgr:-MVrKLee2QZDD1Rx6p48:b-yap0hm) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/02432e11b7bbc20585a63701751321aa99718889/tests/Unit/Classes/DnsRecordBase.tests.ps1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Ah, I see we are returning the same as `[void]` does. Learned something new today. :slightly_smiling_face: 
</blockquote></details>

That was an interesting one to track down in the dev process.


<!-- Sent from Reviewable.io -->

2021-03-16 07:37 UTC, Sudman1 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 31 of 41 files reviewed, 6 unresolved discussions (waiting on @johlju)

___
*[source/en-US/DnsRecordSrvScoped.strings.psd1, line 8 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVkC54E-roAZ2WUBtl9:-MVtxtsD99Kzk33yiGGH:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/en-US/DnsRecordSrvScoped.strings.psd1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We'll go with your suggested option 2.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 07:48 UTC, Sudman1 reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 31 of 41 files reviewed, 6 unresolved discussions (waiting on @johlju)

___
*[source/Classes/002.DnsRecordSrv.ps1, line 94 at r5](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVk8_sA5OlX2fxD2ncj:-MVu-JMf9vn1MtODa7vm:bip2pxl) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/92cbb2a4e8ca42fe01f1f9ad8fc38509386147b9/source/Classes/002.DnsRecordSrv.ps1#L94)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

What would you say to creating a non-DSC method to get the localized data instead of simply saving it in variables? It would make getting the strings easier, would unclutter the resulting psm1 file (not that it matters so much) and would add a bit of complexity to the DnsRecordBase class, but I feel like it would be a cleaner implementation.
</blockquote></details>

turns out it wasn't that complex. Done.


<!-- Sent from Reviewable.io -->

2021-03-16 15:53 UTC, johlju requested changes
> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: 32 of 41 files reviewed, 2 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 51 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvgR6I8mA_SnJJwdxu:-MVvgR6I8mA_SnJJwdxv:b-jl8yo9) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L51)):*
> ```
> if ($this.GetType().Name.StartsWith('Mock'))
> ```

Not really liking that there is production code to handle unit tests. :confused:  Is it possible to refactor this? Maybe we can check if `$null -eq $localizedData` and then load the strings, then a unit test can set the hidden parameter? Or can we pass in the localized strings filename as a variable in the constructor, e.g. 'DnsRecordBase', 'DnsRecordSrv'? 
___
*[source/Classes/001.DnsRecordBase.ps1, line 55 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvjAec0mhZwiJ5HPTs:-MVvjAedCHYQ5itz8A7J:b-dyl3s2) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L55)):*
> ```
> else {
> ```

We should have open brace on a separate line. 

Starting to feel like the custom PSScriptAnalyzer rules do not run for classes. :disappointed: It should have been caught by the HQRM tests. I will submit an issue for that to DscResource.Test.
___
*[source/en-US/DnsRecordSrvScoped.strings.psd1, line 1 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVviO-K5DH04oEpaz-r:-MVviO-K5DH04oEpaz-s:bykqu2u) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/en-US/DnsRecordSrvScoped.strings.psd1#L1)):*
> ```PowerShell
> <#
> ```

Informational. This can be done in another PR if it is possible. Looking at the localized strings files I wonder if it would be possible to have one localized string file for the base class, the localized string file only have the strings that should be overridden, that are resource specific.


<!-- Sent from Reviewable.io -->

2021-03-16 16:00 UTC, johlju reviewed
> Reviewed 7 of 34 files at r1, 2 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: all files reviewed, 2 unresolved discussions (waiting on @Sudman1)



<!-- Sent from Reviewable.io -->

2021-03-16 16:01 UTC, johlju commented
I have review all files now. Just two comments left. 🙂 Awesome work on this! 😃

2021-03-16 19:31 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201)* status: all files reviewed, 2 unresolved discussions (waiting on @Sudman1)

___
*[source/Classes/001.DnsRecordBase.ps1, line 51 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvgR6I8mA_SnJJwdxu:-MVwVv534WpFtrFw1LMu:bu6cftx) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> if ($this.GetType().Name.StartsWith('Mock'))
> ```

Not really liking that there is production code to handle unit tests. :confused:  Is it possible to refactor this? Maybe we can check if `$null -eq $localizedData` and then load the strings, then a unit test can set the hidden parameter? Or can we pass in the localized strings filename as a variable in the constructor, e.g. 'DnsRecordBase', 'DnsRecordSrv'? 
</blockquote></details>

It might help if we just move all strings to the same localized string file instead of have separate files?  :thinking: 


<!-- Sent from Reviewable.io -->

2021-03-16 19:32 UTC, Sudman1 reviewed
Thanks. I've found it very fun. And once I update my template, these will almost write themselves. 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-:-MVvyKB8B6Mvc63fCo6e:byquotj)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/Classes/001.DnsRecordBase.ps1, line 51 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvgR6I8mA_SnJJwdxu:-MVvyYk697hubf1WEbA4:b-hbho9c) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

It might help if we just move all strings to the same localized string file instead of have separate files?  :thinking: 
</blockquote></details>

Me neither. I did it this way because it was simple and to keep the momentum going. But to your point later on, I think this requires a bit more complex solution that maybe populates the localizedData variable from parent classes, adding or overwriting values down the inheritance tree. This should streamline the localization files as well.

Working it now.
___
*[source/Classes/001.DnsRecordBase.ps1, line 55 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvjAec0mhZwiJ5HPTs:-MVwNNPsEpLWjDGEDshH:b-u425wi) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L55)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> else {
> ```

We should have open brace on a separate line. 

Starting to feel like the custom PSScriptAnalyzer rules do not run for classes. :disappointed: It should have been caught by the HQRM tests. I will submit an issue for that to DscResource.Test.
</blockquote></details>

Yeah - sorry. I find this style very difficult. I learned coding in Java and in PowerShell, when you have a scriptblock as an argument, you can't put the opening brace on the next line without escaping the carriage return, so having the braces on the same line reduces the amount of thinking I have to do and makes it easier for those PowerShell novices I work with to understand and relicate. But I understand the style guides call for it. Done.
___
*[source/en-US/DnsRecordSrvScoped.strings.psd1, line 1 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVviO-K5DH04oEpaz-r:-MVwRhy42_PmBWv3wP-t:bvpdxej) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/en-US/DnsRecordSrvScoped.strings.psd1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Informational. This can be done in another PR if it is possible. Looking at the localized strings files I wonder if it would be possible to have one localized string file for the base class, the localized string file only have the strings that should be overridden, that are resource specific.
</blockquote></details>

This is addressed in the earlier comment


<!-- Sent from Reviewable.io -->

2021-03-17 01:30 UTC, Sudman1 reviewed
I think you'll find the solution for handling localization more palatable.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-:-MVxnWKFBONkZC52HYCN:bw9k2vj)* status: 38 of 41 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/Classes/001.DnsRecordBase.ps1, line 51 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvgR6I8mA_SnJJwdxu:-MVxnOpPAfG5oWyPViEj:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L51)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Me neither. I did it this way because it was simple and to keep the momentum going. But to your point later on, I think this requires a bit more complex solution that maybe populates the localizedData variable from parent classes, adding or overwriting values down the inheritance tree. This should streamline the localization files as well.

Working it now.
</blockquote></details>

Done.
___
*[source/Classes/001.DnsRecordBase.ps1, line 55 at r8](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-MVvjAec0mhZwiJ5HPTs:-MVxlK8E19tmjqsPzIC5:b-896fix) ([raw file](https://github.com/dsccommunity/xdnsserver/blob/0161d7374e23c7dbb9a3f1854433f72c23b4924b/source/Classes/001.DnsRecordBase.ps1#L55)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Yeah - sorry. I find this style very difficult. I learned coding in Java and in PowerShell, when you have a scriptblock as an argument, you can't put the opening brace on the next line without escaping the carriage return, so having the braces on the same line reduces the amount of thinking I have to do and makes it easier for those PowerShell novices I work with to understand and relicate. But I understand the style guides call for it. Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-17 16:46 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/201#-:-MW04A4KDYuVT81nmNkE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sudman1)



<!-- Sent from Reviewable.io -->

2021-03-17 16:54 UTC, johlju commented
I create an issue for this. I wasn't expecting to see that current state and desired state to be equal in the integration test. I would have expected it to just report that the record is missing and not comparing the other properties. 🤔 

```
VERBOSE: [fv-az59-142]: LCM:  [ Start  Test     ]  [[DnsRecordSrv]Integration_Test]
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] Calling GetResourceRecord() from the DnsRecordSrv class to get the object's current state.
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] Getting DNS record '_dummy._tcp' with target of 'dummy.contoso.com' (SRV) in zone 'srv.test' from 'localhost'.
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] A matching DNS resource record not found.
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.String') for property 'SymbolicName' does match. Current state is 'dummy' and desired state is 'dummy'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.UInt16') for property 'Weight' does match. Current state is '20' and desired state is '20'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.String') for property 'DnsServer' does match. Current state is 'localhost' and desired state is 'localhost'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.String') for property 'ZoneName' does match. Current state is 'srv.test' and desired state is 'srv.test'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.UInt16') for property 'Port' does match. Current state is '33179' and desired state is '33179'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.String') for property 'Target' does match. Current state is 'dummy.contoso.com' and desired state is 'dummy.contoso.com'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] NOTMATCH: Value (type 'Ensure') for property 'Ensure' does not match. Current state is 'Absent' and desired state is 'Present'. (DRC0021)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.UInt16') for property 'Priority' does match. Current state is '10' and desired state is '10'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] MATCH: Value (type 'System.String') for property 'Protocol' does match. Current state is 'TCP' and desired state is 'TCP'. (DRC0020)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] Compare-DscParameterState result : Property 'Ensure' is in desired state 'False' . (DRC0026)
VERBOSE: [fv-az59-142]:                            [[DnsRecordSrv]Integration_Test] DNS record is NOT in the desired state.
VERBOSE: [fv-az59-142]: LCM:  [ End    Test     ]  [[DnsRecordSrv]Integration_Test]  in 0.5560 seconds.
```

2021-03-17 16:55 UTC, merged

2021-03-17 16:55 UTC, johlju commented
@Sudman1 again, awesome work on this! Now the next one will go fast to review 😃